### GET Wishlist
GET http://localhost:3000/2

### Checka se uma wishlist existe
GET http://localhost:3000/1/check-exists

### Atualiza uma wishlist
PUT http://localhost:3000/1
Content-Type: application/json

{
  "name": "Sempre Tem",
  "items": [
    {
      "name": "Batata Inglesa",
      "priceInCents": 1000,
      "category": "Feira"
    },
    {
      "name": "Carne Moída",
      "priceInCents": 2000,
      "category": "Carnes"
    }
  ]
}

### Cria uma wishlist
POST http://localhost:3000
Content-Type: application/json

{
  "name": "Wishlist 2"
}


